data = {'arise': {'подниматься': '\nbase_form: arise\npast_simple: arose\npast_participle: arisen'},
        'awake': {'пробуждать': '\nbase_form: awake\npast_simple: awoke\npast_participle: awoken'},
        'be': {'быть': '\nbase_form: be\npast_simple: was(were)\npast_participle: been'},
        'bear': {'рожать, переносить': '\nbase_form: bear\npast_simple: bore\npast_participle: born'},
        'beat': {'бить': '\nbase_form: beat\npast_simple: beat\npast_participle: beaten'},
        'become': {'становиться': '\nbase_form: become\npast_simple: became\npast_participle: become'},
        'begin': {'начинать': '\nbase_form: begin\npast_simple: began\npast_participle: begun'},
        'bend': {'наклонять': '\nbase_form: bend\npast_simple: bent\npast_participle: bent'},
        'bet': {'заключать пари': '\nbase_form: bet\npast_simple: bet\npast_participle: bet'},
        'bite': {'кусать': '\nbase_form: bite\npast_simple: bit\npast_participle: bitten'},
        'bleed': {'кровоточить': '\nbase_form: bleed\npast_simple: bled\npast_participle: bled'},
        'blow': {'дуть': '\nbase_form: blow\npast_simple: blew\npast_participle: blown'},
        'break': {'ломать': '\nbase_form: break\npast_simple: broke\npast_participle: broken'},
        'breed': {'разводить животных': '\nbase_form: breed\npast_simple: bred\npast_participle: bred'},
        'bring': {'приносить': '\nbase_form: bring\npast_simple: brought\npast_participle: brought'},
        'build': {'строить': '\nbase_form: build\npast_simple: built\npast_participle: built'},
        'buy': {'покупать': '\nbase_form: buy\npast_simple: bought\npast_participle: bought'},
        'catch': {'ловить': '\nbase_form: catch\npast_simple: caught\npast_participle: caught'},
        'choose': {'выбирать': '\nbase_form: choose\npast_simple: chose\npast_participle: chosen'},
        'cling': {'цепляться': '\nbase_form: cling\npast_simple: clung\npast_participle: clung'},
        'come': {'приходить': '\nbase_form: come\npast_simple: came\npast_participle: come'},
        'cost': {'стоить': '\nbase_form: cost\npast_simple: cost\npast_participle: cost'},
        'deal': {'вести дела': '\nbase_form: deal\npast_simple: dealt\npast_participle: dealt'},
        'dig': {'копать': '\nbase_form: dig\npast_simple: dug\npast_participle: dug'},
        'do': {'делать': '\nbase_form: do\npast_simple: did\npast_participle: done'},
        'draw': {'рисовать, тянуть': '\nbase_form: draw\npast_simple: drew\npast_participle: drawn'},
        'drink': {'пить': '\nbase_form: drink\npast_simple: drank\npast_participle: drunk'},
        'drive': {'водить автомобиль': '\nbase_form: drive\npast_simple: drove\npast_participle: driven'},
        'fall': {'падать': '\nbase_form: fall\npast_simple: fell\npast_participle: fallen'},
        'feed': {'кормить': '\nbase_form: feed\npast_simple: fed\npast_participle: fed'},
        'feel': {'чувствовать': '\nbase_form: feel\npast_simple: felt\npast_participle: felt'},
        'fight': {'бороться': '\nbase_form: fight\npast_simple: fought\npast_participle: fought'},
        'find': {'находить': '\nbase_form: find\npast_simple: found\npast_participle: found'},
        'flee': {'сбегать': '\nbase_form: flee\npast_simple: fled\npast_participle: fled'},
        'fly': {'летать': '\nbase_form: fly\npast_simple: flew\npast_participle: flown'},
        'forbid': {'запрещать': '\nbase_form: forbid\npast_simple: forbade\npast_participle: forbidden'},
        'forget': {'забывать': '\nbase_form: forget\npast_simple: forgot\npast_participle: forgotten'},
        'forgive': {'прощать': '\nbase_form: forgive\npast_simple: forgave\npast_participle: forgiven'},
        'get': {'получать': '\nbase_form: get\npast_simple: got\npast_participle: got (gotten)'},
        'give': {'давать': '\nbase_form: give\npast_simple: gave\npast_participle: given'},
        'go': {'идти': '\nbase_form: go\npast_simple: went\npast_participle: gone'},
        'grow': {'расти': '\nbase_form: grow\npast_simple: grew\npast_participle: grown'},
        'hang': {'висеть': '\nbase_form: hang\npast_simple: hung\npast_participle: hung'},
        'have': {'иметь': '\nbase_form: have\npast_simple: had\npast_participle: had'},
        'hear': {'слышать': '\nbase_form: hear\npast_simple: heard\npast_participle: heard'},
        'freeze': {'замораживать': '\nbase_form: freeze\npast_simple: froze\npast_participle: frozen'},
        'hide': {'прятать': '\nbase_form: hide\npast_simple: hid\npast_participle: hidden'},
        'hit': {'ударять, попадать': '\nbase_form: hit\npast_simple: hit\npast_participle: hit'},
        'hold': {'держать': '\nbase_form: hold\npast_simple: held\npast_participle: held'},
        'hurt': {'причинять боль': '\nbase_form: hurt\npast_simple: hurt\npast_participle: hurt'},
        'keep': {'сохранять, соблюдать': '\nbase_form: keep\npast_simple: kept\npast_participle: kept'},
        'know': {'знать': '\nbase_form: know\npast_simple: knew\npast_participle: known'},
        'lay': {'класть': '\nbase_form: lay\npast_simple: laid\npast_participle: laid'},
        'lead': {'вести, лидировать': '\nbase_form: lead\npast_simple: led\npast_participle: led'},
        'learn': {'учиться, узнавать': '\nbase_form: learn\npast_simple: learnt (learned)\npast_participle: learnt (learned)'},
        'leave': {'покидать, оставлять': '\nbase_form: leave\npast_simple: left\npast_participle: left'},
        'lend': {'давать взаймы': '\nbase_form: lend\npast_simple: lent\npast_participle: lent'},
        'let': {'позволять': '\nbase_form: let\npast_simple: let\npast_participle: let'},
        'lie': {'лежать': '\nbase_form: lie\npast_simple: lay\npast_participle: lain'},
        'light': {'зажигать, освещать': '\nbase_form: light\npast_simple: lit\npast_participle: lit'},
        'lose': {'терять': '\nbase_form: lose\npast_simple: lost\npast_participle: lost'},
        'make': {'делать, мастерить': '\nbase_form: make\npast_simple: made\npast_participle: made'},
        'mean': {'значить': '\nbase_form: mean\npast_simple: meant\npast_participle: meant'},
        'meet': {'встречать, знакомиться': '\nbase_form: meet\npast_simple: met\npast_participle: met'},
        'pay': {'платить': '\nbase_form: pay\npast_simple: paid\npast_participle: paid'},
        'put': {'класть, ставить': '\nbase_form: put\npast_simple: put\npast_participle: put'},
        'read': {'читать': '\nbase_form: read\npast_simple: read\npast_participle: read'},
        'ride': {'ездить верхом': '\nbase_form: ride\npast_simple: rode\npast_participle: ridden'},
        'ring': {'звонить': '\nbase_form: ring\npast_simple: rang\npast_participle: rung'},
        'rise': {'возрастать, подниматься': '\nbase_form: rise\npast_simple: rose\npast_participle: risen'},
        'run': {'бежать': '\nbase_form: run\npast_simple: ran\npast_participle: run'},
        'say': {'сказать': '\nbase_form: say\npast_simple: said\npast_participle: said'},
        'see': {'видеть': '\nbase_form: see\npast_simple: saw\npast_participle: seen'},
        'seek': {'искать': '\nbase_form: seek\npast_simple: sought\npast_participle: sought'},
        'sell': {'продавать': '\nbase_form: sell\npast_simple: sold\npast_participle: sold'},
        'send': {'посылать': '\nbase_form: send\npast_simple: sent\npast_participle: sent'},
        'set': {'устанавливать': '\nbase_form: set\npast_simple: set\npast_participle: set'},
        'shake': {'трясти': '\nbase_form: shake\npast_simple: shook\npast_participle: shaken'},
        'shine': {'светить, сиять': '\nbase_form: shine\npast_simple: shone\npast_participle: shone'},
        'shoot': {'стрелять': '\nbase_form: shoot\npast_simple: shot\npast_participle: shot'},
        'show': {'показывать': '\nbase_form: show\npast_simple: showed\npast_participle: shown'},
        'shrink': {'сжиматься': '\nbase_form: shrink\npast_simple: shrank\npast_participle: shrunk'},
        'shut': {'закрывать, затворять': '\nbase_form: shut\npast_simple: shut\npast_participle: shut'},
        'sing': {'петь': '\nbase_form: sing\npast_simple: sang\npast_participle: sung'},
        'sit': {'сидеть': '\nbase_form: sit\npast_simple: sat\npast_participle: sat'},
        'sleep': {'спать': '\nbase_form: sleep\npast_simple: slept\npast_participle: slept'},
        'slide': {'скользить': '\nbase_form: slide\npast_simple: slid\npast_participle: slid'},
        'smell': {'пахнуть, нюхать': '\nbase_form: smell\npast_simple: smelt\npast_participle: smelt'},
        'speak': {'говорить': '\nbase_form: speak\npast_simple: spoke\npast_participle: spoken'},
        'spell': {'произносить или писать по буквам': '\nbase_form: spell\npast_simple: spelt (spelled)\npast_participle: spelt (spelled)'},
        'spill': {'разлить': '\nbase_form: spill\npast_simple: spilt (spilled)\npast_participle: spilt (spilled)'},
        'spin': {'крутить': '\nbase_form: spin\npast_simple: spun\npast_participle: spun'},
        'split': {'разделять, раскалывать': '\nbase_form: split\npast_simple: split\npast_participle: split'},
        'spoil': {'портить': '\nbase_form: spoil\npast_simple: spoilt (spoiled)\npast_participle: spoilt (spoiled)'},
        'spread': {'разворачивать, распространять': '\nbase_form: spread\npast_simple: spread\npast_participle: spread'},
        'stand': {'стоять': '\nbase_form: stand\npast_simple: stood\npast_participle: stood'},
        'steal': {'воровать': '\nbase_form: steal\npast_simple: stole\npast_participle: stolen'},
        'sting': {'жалить': '\nbase_form: sting\npast_simple: stung\npast_participle: stung'},
        'stink': {'вонять': '\nbase_form: stink\npast_simple: stank\npast_participle: stunk'},
        'strike': {'бастовать, ударять': '\nbase_form: strike\npast_simple: struck\npast_participle: struck'},
        'swear': {'клясться, ругаться': '\nbase_form: swear\npast_simple: swore\npast_participle: sworn'},
        'sweep': {'подметать': '\nbase_form: sweep\npast_simple: swept\npast_participle: swept'},
        'swell': {'опухать': '\nbase_form: swell\npast_simple: swelled\npast_participle: swollen (swelled)'},
        'swim': {'плавать': '\nbase_form: swim\npast_simple: swam\npast_participle: swum'},
        'take': {'брать': '\nbase_form: take\npast_simple: took\npast_participle: taken'},
        'teach': {'обучать': '\nbase_form: teach\npast_simple: taught\npast_participle: taught'},
        'tear': {'рвать': '\nbase_form: tear\npast_simple: tore\npast_participle: torn'},
        'tell': {'рассказывать': '\nbase_form: tell\npast_simple: told\npast_participle: told'},
        'think': {'думать': '\nbase_form: think\npast_simple: thought\npast_participle: thought'},
        'throw': {'бросать': '\nbase_form: throw\npast_simple: threw\npast_participle: thrown'},
        'understand': {'понимать': '\nbase_form: understand\npast_simple: understood\npast_participle: understood'},
        'wake': {'будить': '\nbase_form: wake\npast_simple: woke\npast_participle: woken'},
        'wear': {'носить (одежду)': '\nbase_form: wear\npast_simple: wore\npast_participle: worn'},
        'win': {'побеждать': '\nbase_form: win\npast_simple: won\npast_participle: won'},
        'wind': {'обматывать, изгибаться': '\nbase_form: wind\npast_simple: wound\npast_participle: wound'},
        'write': {'писать': '\nbase_form: write\npast_simple: wrote\npast_participle: written'},
        }